// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID         uuid.UUID
	Status     string
	Type       string
	ExpiryDate time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
