apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler-pods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-pods
  template:
    metadata:
      labels:
        app: scheduler-pods
    spec:
      containers:
        - name: scheduler
          image: cbascheduler
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: 
            limits: 
              cpu: '1'
              memory: '2000Mi'

          
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-srv
spec:
  type: LoadBalancer
  selector:
    app: scheduler-pods
  ports:
    - name: rpc-scheduler
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: rest-scheduler
      protocol: TCP
      port: 8080
      targetPort: 8080